// <auto-generated />
using System;
using ClinicaSaaS.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicaSaaS.Persistence.Migrations
{
    [DbContext(typeof(ClinicaSaaSDbContext))]
    partial class ClinicaSaaSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicaSaaS.Domain.Billing.Entities.FacturaDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Descripcion");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FacturaId");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioUnitario");

                    b.Property<Guid?>("ProcedimientoRealizadoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProcedimientoRealizadoId");

                    b.Property<decimal>("SubtotalAlmacenado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Subtotal");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("ProcedimientoRealizadoId");

                    b.ToTable("FacturaDetalles", "Billing");
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Billing.Entities.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaAnulado")
                        .HasColumnType("bit")
                        .HasColumnName("EstaAnulado");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FacturaId");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaHora");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MetodoPago");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Monto");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("MotivoAnulacion");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Referencia");

                    b.Property<Guid>("RegistradoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RegistradoPorUsuarioId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("FechaHora");

                    b.ToTable("Pagos", "Billing");
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Billing.Factura", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClinicaId");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreadoPorUsuarioId");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Descuento");

                    b.Property<Guid?>("EliminadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EliminadoPorUsuarioId");

                    b.Property<bool>("EstaAnulada")
                        .HasColumnType("bit")
                        .HasColumnName("EstaAnulada");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit")
                        .HasColumnName("EstaEliminado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Estado");

                    b.Property<string>("EstadoDGII")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("EstadoDGII");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEliminacion");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEmision");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Impuestos")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Impuestos");

                    b.Property<Guid?>("ModificadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("MotivoAnulacion");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NumeroComprobante");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PacienteId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("SubtotalAlmacenado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Subtotal");

                    b.Property<string>("TipoFactura")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("TipoFactura");

                    b.Property<decimal>("TotalAlmacenado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ClinicaId", "FechaEmision");

                    b.HasIndex("ClinicaId", "NumeroComprobante")
                        .IsUnique()
                        .HasFilter("[NumeroComprobante] IS NOT NULL");

                    b.ToTable("Facturas", "Billing");
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Billing.SecuenciaComprobante", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClinicaId");

                    b.Property<bool>("EsElectronico")
                        .HasColumnType("bit")
                        .HasColumnName("EsElectronico");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("FechaVencimiento");

                    b.Property<long>("SecuenciaActual")
                        .HasColumnType("bigint")
                        .HasColumnName("SecuenciaActual");

                    b.Property<long>("SecuenciaDesde")
                        .HasColumnType("bigint")
                        .HasColumnName("SecuenciaDesde");

                    b.Property<long>("SecuenciaHasta")
                        .HasColumnType("bigint")
                        .HasColumnName("SecuenciaHasta");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("TipoComprobante");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId", "TipoComprobante")
                        .IsUnique();

                    b.ToTable("SecuenciasComprobante", "Billing");
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Clinical.Entities.ArchivoClinico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EliminadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EliminadoPorUsuarioId");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit")
                        .HasColumnName("EstaEliminado");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEliminacion");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaSubida");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .HasColumnName("HashSHA256")
                        .IsFixedLength();

                    b.Property<Guid>("HistorialClinicoEntradaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("HistorialClinicoEntradaId");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("NombreOriginal");

                    b.Property<string>("RutaAlmacenamiento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("RutaAlmacenamiento");

                    b.Property<Guid>("SubidoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SubidoPorUsuarioId");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("TamanoBytes");

                    b.Property<string>("TipoArchivo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TipoArchivo");

                    b.HasKey("Id");

                    b.HasIndex("HistorialClinicoEntradaId");

                    b.ToTable("ArchivosClinicos", "Clinical");
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Clinical.Entities.HistorialClinicoEntrada", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CitaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CitaId");

                    b.Property<string>("Diagnostico")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Diagnostico");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DoctorId");

                    b.Property<Guid?>("EntradaAnteriorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntradaAnteriorId");

                    b.Property<bool>("EsVersionActual")
                        .HasColumnType("bit")
                        .HasColumnName("EsVersionActual");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaRegistro");

                    b.Property<Guid>("HistorialClinicoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("HistorialClinicoId");

                    b.Property<string>("MotivoConsulta")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MotivoConsulta");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Notas");

                    b.Property<string>("SignosVitales")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SignosVitalesJson");

                    b.Property<string>("Tratamiento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tratamiento");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("EntradaAnteriorId");

                    b.HasIndex("HistorialClinicoId", "EsVersionActual");

                    b.HasIndex("HistorialClinicoId", "Version")
                        .IsUnique();

                    b.ToTable("HistorialClinicoEntradas", "Clinical");
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Clinical.Entities.ProcedimientoRealizado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DoctorId");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha");

                    b.Property<Guid>("HistorialClinicoEntradaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("HistorialClinicoEntradaId");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Notas");

                    b.Property<string>("PiezaDental")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PiezaDental");

                    b.Property<decimal>("PrecioAplicado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioAplicado");

                    b.Property<Guid>("ProcedimientoCatalogoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProcedimientoCatalogoId");

                    b.HasKey("Id");

                    b.HasIndex("HistorialClinicoEntradaId");

                    b.HasIndex("ProcedimientoCatalogoId");

                    b.ToTable("ProcedimientosRealizados", "Clinical");
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Clinical.HistorialClinico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClinicaId");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PacienteId");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId")
                        .IsUnique();

                    b.ToTable("HistorialesClinicos", "Clinical");
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Clinical.ProcedimientoCatalogo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClinicaId");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Codigo");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreadoPorUsuarioId");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descripcion");

                    b.Property<Guid?>("EliminadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EliminadoPorUsuarioId");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit")
                        .HasColumnName("EstaEliminado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEliminacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaModificacion");

                    b.Property<Guid?>("ModificadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ModificadoPorUsuarioId");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Nombre");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioBase");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId", "Codigo")
                        .IsUnique();

                    b.ToTable("ProcedimientosCatalogo", "Clinical");
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Personal.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClinicaId");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreadoPorUsuarioId");

                    b.Property<Guid?>("EliminadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EliminadoPorUsuarioId");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Especialidad");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit")
                        .HasColumnName("EstaEliminado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEliminacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaModificacion");

                    b.Property<Guid?>("ModificadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ModificadoPorUsuarioId");

                    b.Property<string>("NumeroExequatur")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NumeroExequatur");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "ClinicaId")
                        .IsUnique();

                    b.ToTable("Doctores", "Personal");
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Personal.Empleado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Cargo");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClinicaId");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreadoPorUsuarioId");

                    b.Property<Guid?>("EliminadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EliminadoPorUsuarioId");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit")
                        .HasColumnName("EstaEliminado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEliminacion");

                    b.Property<DateOnly?>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("FechaIngreso");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaModificacion");

                    b.Property<Guid?>("ModificadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ModificadoPorUsuarioId");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "ClinicaId")
                        .IsUnique();

                    b.ToTable("Empleados", "Personal");
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Personal.Entities.HorarioDoctor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<Guid?>("ConsultorioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ConsultorioId");

                    b.Property<byte?>("DiaSemana")
                        .HasColumnType("tinyint")
                        .HasColumnName("DiaSemana");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DoctorId");

                    b.Property<bool>("EstaEliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("EstaEliminado");

                    b.Property<string>("TipoHorario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TipoHorario");

                    b.HasKey("Id");

                    b.HasIndex("ConsultorioId");

                    b.HasIndex("DoctorId");

                    b.ToTable("HorariosDoctor", "Scheduling");
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Personal.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Apellidos");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClinicaId");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreadoPorUsuarioId");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Direccion");

                    b.Property<Guid?>("EliminadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EliminadoPorUsuarioId");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Email");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit")
                        .HasColumnName("EstaEliminado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEliminacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaModificacion");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("FechaNacimiento");

                    b.Property<string>("Genero")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("Sexo")
                        .IsFixedLength();

                    b.Property<Guid?>("ModificadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ModificadoPorUsuarioId");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nombres");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Telefono");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId", "Apellidos", "Nombres");

                    b.ToTable("Pacientes", "Personal");
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Scheduling.Cita", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClinicaId");

                    b.Property<Guid?>("ConsultorioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ConsultorioId");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreadoPorUsuarioId");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DoctorId");

                    b.Property<Guid?>("EliminadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EliminadoPorUsuarioId");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit")
                        .HasColumnName("EstaEliminado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEliminacion");

                    b.Property<DateTime>("FechaHoraFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaHoraFin");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaHoraInicio");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaModificacion");

                    b.Property<Guid?>("ModificadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ModificadoPorUsuarioId");

                    b.Property<string>("MotivoConsulta")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("MotivoConsulta");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PacienteId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ConsultorioId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ClinicaId", "FechaHoraInicio");

                    b.HasIndex("DoctorId", "FechaHoraInicio");

                    b.ToTable("Citas", "Scheduling");
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Scheduling.Consultorio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClinicaId");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreadoPorUsuarioId");

                    b.Property<Guid?>("EliminadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EliminadoPorUsuarioId");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit")
                        .HasColumnName("EstaEliminado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEliminacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaModificacion");

                    b.Property<Guid?>("ModificadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ModificadoPorUsuarioId");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Piso")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Piso");

                    b.HasKey("Id");

                    b.ToTable("Consultorios", "Scheduling");
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Scheduling.Equipamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClinicaId");

                    b.Property<Guid?>("ConsultorioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ConsultorioId");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreadoPorUsuarioId");

                    b.Property<Guid?>("EliminadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EliminadoPorUsuarioId");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit")
                        .HasColumnName("EstaEliminado");

                    b.Property<DateOnly?>("FechaAdquisicion")
                        .HasColumnType("date")
                        .HasColumnName("FechaAdquisicion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEliminacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaModificacion");

                    b.Property<Guid?>("ModificadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ModificadoPorUsuarioId");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nombre");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NumeroSerie");

                    b.Property<DateOnly?>("ProximoMantenimiento")
                        .HasColumnType("date")
                        .HasColumnName("ProximoMantenimiento");

                    b.HasKey("Id");

                    b.HasIndex("ConsultorioId");

                    b.ToTable("Equipamiento", "Scheduling");
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Security.Clinica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreadoPorUsuarioId");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Direccion");

                    b.Property<Guid?>("EliminadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EliminadoPorUsuarioId");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Email");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit")
                        .HasColumnName("EstaEliminado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEliminacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaModificacion");

                    b.Property<Guid?>("ModificadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ModificadoPorUsuarioId");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NombreComercial");

                    b.Property<string>("PlanSuscripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PlanSuscripcion");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("RazonSocial");

                    b.Property<string>("Rnc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("RNC");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Telefono");

                    b.HasKey("Id");

                    b.HasIndex("Rnc")
                        .IsUnique();

                    b.ToTable("Clinicas", "Security");
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Security.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreadoPorUsuarioId");

                    b.Property<Guid?>("EliminadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EliminadoPorUsuarioId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Email");

                    b.Property<bool>("EsSuperAdminSaaS")
                        .HasColumnType("bit")
                        .HasColumnName("EsSuperAdminSaaS");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit")
                        .HasColumnName("EstaEliminado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEliminacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaModificacion");

                    b.Property<Guid?>("ModificadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ModificadoPorUsuarioId");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NombreCompleto");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varbinary(256)")
                        .HasColumnName("PasswordHash");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Telefono");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", "Security");
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Security.UsuarioClinicaRol", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<Guid?>("AsignadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AsignadoPorUsuarioId");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClinicaId");

                    b.Property<Guid?>("EliminadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EliminadoPorUsuarioId");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit")
                        .HasColumnName("EstaEliminado");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaAsignacion");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEliminacion");

                    b.Property<int>("Rol")
                        .HasColumnType("int")
                        .HasColumnName("RolId");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("AsignadoPorUsuarioId");

                    b.HasIndex("ClinicaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId", "ClinicaId", "Rol")
                        .IsUnique();

                    b.ToTable("UsuarioClinicaRoles", "Security");
                });

            modelBuilder.Entity("ClinicaSaaS.Persistence.Audit.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Accion");

                    b.Property<Guid?>("ClinicaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClinicaId");

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DatosAnteriores");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DatosNuevos");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DireccionIP");

                    b.Property<string>("Dispositivo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Dispositivo");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EntidadId");

                    b.Property<string>("EntidadNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EntidadNombre");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaHora");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ClinicaId", "FechaHora");

                    b.HasIndex("EntidadNombre", "EntidadId");

                    b.ToTable("Auditoria", "Audit", t =>
                        {
                            t.HasCheckConstraint("CK_Auditoria_Accion", "Accion IN ('Create','Update','Delete','Login','Logout','Anular','Exportar')");
                        });
                });

            modelBuilder.Entity("ClinicaSaaS.Persistence.Security.RolLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles", "Security");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "AdminClinica"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Recepcion"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Doctor"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Empleado"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Auditor"
                        });
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Billing.Entities.FacturaDetalle", b =>
                {
                    b.HasOne("ClinicaSaaS.Domain.Billing.Factura", null)
                        .WithMany("Detalles")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaSaaS.Domain.Clinical.Entities.ProcedimientoRealizado", null)
                        .WithMany()
                        .HasForeignKey("ProcedimientoRealizadoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Billing.Entities.Pago", b =>
                {
                    b.HasOne("ClinicaSaaS.Domain.Billing.Factura", null)
                        .WithMany("Pagos")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Clinical.Entities.ArchivoClinico", b =>
                {
                    b.HasOne("ClinicaSaaS.Domain.Clinical.Entities.HistorialClinicoEntrada", null)
                        .WithMany("Archivos")
                        .HasForeignKey("HistorialClinicoEntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Clinical.Entities.HistorialClinicoEntrada", b =>
                {
                    b.HasOne("ClinicaSaaS.Domain.Clinical.Entities.HistorialClinicoEntrada", null)
                        .WithMany()
                        .HasForeignKey("EntradaAnteriorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicaSaaS.Domain.Clinical.HistorialClinico", null)
                        .WithMany("Entradas")
                        .HasForeignKey("HistorialClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Clinical.Entities.ProcedimientoRealizado", b =>
                {
                    b.HasOne("ClinicaSaaS.Domain.Clinical.Entities.HistorialClinicoEntrada", null)
                        .WithMany("ProcedimientosRealizados")
                        .HasForeignKey("HistorialClinicoEntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaSaaS.Domain.Clinical.ProcedimientoCatalogo", null)
                        .WithMany()
                        .HasForeignKey("ProcedimientoCatalogoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Personal.Entities.HorarioDoctor", b =>
                {
                    b.HasOne("ClinicaSaaS.Domain.Personal.Doctor", null)
                        .WithMany("Horarios")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ClinicaSaaS.Domain.Personal.ValueObjects.BloqueHorario", "Bloque", b1 =>
                        {
                            b1.Property<Guid>("HorarioDoctorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<TimeOnly>("HoraFin")
                                .HasColumnType("time")
                                .HasColumnName("HoraFin");

                            b1.Property<TimeOnly>("HoraInicio")
                                .HasColumnType("time")
                                .HasColumnName("HoraInicio");

                            b1.HasKey("HorarioDoctorId");

                            b1.ToTable("HorariosDoctor", "Scheduling");

                            b1.WithOwner()
                                .HasForeignKey("HorarioDoctorId");
                        });

                    b.OwnsOne("ClinicaSaaS.Domain.Personal.ValueObjects.PeriodoVigencia", "Vigencia", b1 =>
                        {
                            b1.Property<Guid>("HorarioDoctorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly?>("FechaFin")
                                .HasColumnType("date")
                                .HasColumnName("FechaFinVigencia");

                            b1.Property<DateOnly>("FechaInicio")
                                .HasColumnType("date")
                                .HasColumnName("FechaInicioVigencia");

                            b1.HasKey("HorarioDoctorId");

                            b1.ToTable("HorariosDoctor", "Scheduling");

                            b1.WithOwner()
                                .HasForeignKey("HorarioDoctorId");
                        });

                    b.Navigation("Bloque")
                        .IsRequired();

                    b.Navigation("Vigencia")
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Personal.Paciente", b =>
                {
                    b.OwnsOne("ClinicaSaaS.Domain.Personal.ValueObjects.ContactoEmergencia", "ContactoEmergencia", b1 =>
                        {
                            b1.Property<Guid>("PacienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("ContactoEmergenciaNombre");

                            b1.Property<string>("Telefono")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("ContactoEmergenciaTelefono");

                            b1.HasKey("PacienteId");

                            b1.ToTable("Pacientes", "Personal");

                            b1.WithOwner()
                                .HasForeignKey("PacienteId");
                        });

                    b.OwnsOne("ClinicaSaaS.Domain.Personal.ValueObjects.DocumentoIdentidad", "Documento", b1 =>
                        {
                            b1.Property<Guid>("PacienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Documento");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("TipoDocumento");

                            b1.HasKey("PacienteId");

                            b1.ToTable("Pacientes", "Personal");

                            b1.WithOwner()
                                .HasForeignKey("PacienteId");
                        });

                    b.Navigation("ContactoEmergencia");

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Scheduling.Cita", b =>
                {
                    b.HasOne("ClinicaSaaS.Domain.Scheduling.Consultorio", null)
                        .WithMany()
                        .HasForeignKey("ConsultorioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicaSaaS.Domain.Personal.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaSaaS.Domain.Personal.Paciente", null)
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Scheduling.Equipamiento", b =>
                {
                    b.HasOne("ClinicaSaaS.Domain.Scheduling.Consultorio", null)
                        .WithMany()
                        .HasForeignKey("ConsultorioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Security.UsuarioClinicaRol", b =>
                {
                    b.HasOne("ClinicaSaaS.Domain.Security.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AsignadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicaSaaS.Domain.Security.Clinica", null)
                        .WithMany()
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaSaaS.Domain.Security.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Billing.Factura", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Clinical.Entities.HistorialClinicoEntrada", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("ProcedimientosRealizados");
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Clinical.HistorialClinico", b =>
                {
                    b.Navigation("Entradas");
                });

            modelBuilder.Entity("ClinicaSaaS.Domain.Personal.Doctor", b =>
                {
                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
